CREATE SEQUENCE document_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE analysis_logs_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE chat_sessions_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE chat_messages_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE audit_logs_seq START WITH 1 INCREMENT BY 1;
CREATE TABLE users (
 user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 email VARCHAR(255) NOT NULL UNIQUE, password VARCHAR(255) NOT NULL,
 name VARCHAR(100) NOT NULL, role VARCHAR(20) NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP
);
CREATE TABLE phishing_keywords (
 keyword_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 keyword VARCHAR(255) NOT NULL UNIQUE, risk_score INTEGER NOT NULL,
 category VARCHAR(255) NOT NULL, description TEXT, active BOOLEAN NOT NULL,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP
);
CREATE TABLE analysis_logs (
 analysis_id BIGINT PRIMARY KEY DEFAULT nextval('analysis_logs_seq'),
 user_id BIGINT NOT NULL REFERENCES users, input_text TEXT NOT NULL,
 risk_level VARCHAR(20) NOT NULL, risk_score INTEGER NOT NULL,
 detected_keywords JSONB, rule_reason TEXT, ai_summary TEXT, recommended_action TEXT,
 created_at TIMESTAMP NOT NULL
);
CREATE TABLE documents (
 document_id BIGINT PRIMARY KEY DEFAULT nextval('document_seq'),
 title VARCHAR(255) NOT NULL, source VARCHAR(100), source_url TEXT,
 file_path TEXT NOT NULL, status VARCHAR(30) NOT NULL, uploaded_by BIGINT REFERENCES users,
 created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP,
 original_file_name VARCHAR(255) NOT NULL, stored_file_name VARCHAR(255) NOT NULL,
 chunk_count INTEGER NOT NULL
);
CREATE TABLE document_chunks (
 chunk_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 document_id BIGINT NOT NULL REFERENCES documents ON DELETE CASCADE,
 chunk_index INTEGER NOT NULL, content TEXT NOT NULL, created_at TIMESTAMP NOT NULL
);
CREATE TABLE chat_sessions (
 session_id BIGINT PRIMARY KEY DEFAULT nextval('chat_sessions_seq'),
 user_id BIGINT NOT NULL REFERENCES users, title VARCHAR(255) NOT NULL,
 deleted BOOLEAN NOT NULL, created_at TIMESTAMP NOT NULL, updated_at TIMESTAMP
);
CREATE TABLE chat_messages (
 message_id BIGINT PRIMARY KEY DEFAULT nextval('chat_messages_seq'),
 session_id BIGINT NOT NULL REFERENCES chat_sessions ON DELETE CASCADE,
 sender VARCHAR(20) NOT NULL, message TEXT NOT NULL, referenced_chunks TEXT,
 created_at TIMESTAMP NOT NULL
);
CREATE TABLE audit_logs (
 audit_id BIGINT PRIMARY KEY DEFAULT nextval('audit_logs_seq'),
 user_id BIGINT REFERENCES users, action VARCHAR(50) NOT NULL, target_type VARCHAR(50) NOT NULL,
 target_id BIGINT, ip_address VARCHAR(100), detail TEXT, created_at TIMESTAMP NOT NULL
);
