CREATE TABLE analysis_reviews (
 review_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 analysis_id BIGINT NOT NULL REFERENCES analysis_logs ON DELETE CASCADE,
 submitted_by BIGINT NOT NULL REFERENCES users,
 feedback_type VARCHAR(255) NOT NULL, comment VARCHAR(1000), status VARCHAR(255) NOT NULL,
 label VARCHAR(255), reviewed_by BIGINT REFERENCES users, reason VARCHAR(1000),
 created_at TIMESTAMPTZ NOT NULL, reviewed_at TIMESTAMPTZ, version BIGINT,
 UNIQUE (analysis_id, submitted_by)
);
CREATE INDEX idx_reviews_status_created ON analysis_reviews(status, created_at DESC);
